blueprint:
  name: Occupants Tracking
  description: "This automation blueprint is designed to keep informed on your occupants whereabout. It will notify you when someone is back or left the home."
  
  domain: automation

  input:
    person_entities:
      name: Occupants
      description: "Choose from the list of 'person' entities to track"
      selector:
        entity:
          domain: person
          multiple: true
    notify_service:
      name: Notify Service
      description: "Enter the Notify Service or script such as notify.pushover or notify.mobile_app_device_name to receive notification when the occupant is home or away."
      default: "notify.pushover"
      selector:
        text:

mode: queued
max_exceeded: silent

variables:
  person_entities: !input 'person_entities'

trigger:
  - platform: state
    entity_id: !input 'person_entities'
    to: 'home'
  - platform: state
    entity_id: !input 'person_entities'
    from: 'home'


action:
  - service: !input 'notify_service'
    data:
      message: >-
        {%- set person = trigger.to_state.name -%}
        {%- set new_state = 'back' if trigger.to_state.state == 'home' else 'away' -%}
        {%- set people_home = states.person | selectattr('entity_id', 'in', person_entities) | selectattr('state', 'eq', 'home') | map(attribute='name') | list -%}
        {%- set people_away = states.person | selectattr('entity_id', 'in', person_entities) | rejectattr('state', 'eq', 'home') | map(attribute='name') | list -%}
        
        {{ person }} is {{ new_state }}. Right now, {{''}}
        {%- set group = people_home if new_state == 'back' else people_away -%}
        {%- set group_last = group[-1] if group|length > 1 else None -%}
        {%- set group_list = group[:-1] | join(', ') -%}
        
        {%- if group|length == person_entities|length -%}
          everyone is {{ 'at home' if new_state == 'back' else 'away' }}
        {%- elif group|length == 1 -%}
          {{ person }} is the only one {{ 'at home' if new_state == 'back' else 'away' }}
        {%- else -%}
          {{ group_list }} and {{ group_last }} are {{ 'at home' if new_state == 'back' else 'away' }}
        {%- endif -%}
