blueprint:
  name: ZWaveJS - Zooz ZEN34 Remote Switch scene controller
  description: |
    Perform actions when Zooz ZEN34 Remote Switch buttons are interacted with.

    A release action is always triggered after a hold action, which makes
    them a bit tricky to use. The hold action is repeated as long as the
    button is held down.

  domain: automation
  input:
    zwavejs_device:
      name: ZWaveJS Device
      description: The Zooz ZEN34 Remote Switch to listen for events on.
      selector:
        device:
          integration: zwave_js
          manufacturer: Zooz
          model: ZEN34
    scene_001_keypressed_actions:
      name: Scene 001 KeyPressed Actions
      selector:
        action:
      default: []
    scene_001_keypressed2x_actions:
      name: Scene 001 KeyPressed2x Actions
      selector:
        action:
      default: []
    scene_001_keypressed3x_actions:
      name: Scene 001 KeyPressed3x Actions
      selector:
        action:
      default: []
    scene_001_keypressed4x_actions:
      name: Scene 001 KeyPressed4x Actions
      selector:
        action:
      default: []
    scene_001_keypressed5x_actions:
      name: Scene 001 KeyPressed5x Actions
      selector:
        action:
      default: []
    scene_002_keypressed_actions:
      name: Scene 002 KeyPressed Actions
      selector:
        action:
      default: []
    scene_002_keypressed2x_actions:
      name: Scene 002 KeyPressed2x Actions
      selector:
        action:
      default: []
    scene_002_keypressed3x_actions:
      name: Scene 002 KeyPressed3x Actions
      selector:
        action:
      default: []
    scene_002_keypressed4x_actions:
      name: Scene 002 KeyPressed4x Actions
      selector:
        action:
      default: []
    scene_002_keypressed5x_actions:
      name: Scene 002 KeyPressed5x Actions
      selector:
        action:
      default: []
    release_sceene_001_actions:
      name: Release Scene 001 Actions
      selector:
        action:
      default: []
    release_scene_002_actions:
      name: Release Scene 002 Actions
      selector:
        action:
      default: []
    hold_scene_001_actions:
      name: Hold Scene 001 Actions
      selector:
        action:
      default: []
    hold_scene_002_actions:
      name: Hold Scene 002 Actions
      selector:
        action:
      default: []

mode: single

# If you haven't upgraded to 2021.4.0 or newer yet, you'll need to use this trigger code instead
#trigger:
#  - platform: event
#    event_type: zwave_js_event
#    event_data:
#      type: value_notification

trigger:
  - platform: event
    event_type: zwave_js_value_notification

variables:
  logger: blueprint.zwavejs_scene_activation
  zwavejs_device: !input zwavejs_device

action:
  - choose:
    # IF triggered device_id is zwavejs_device id
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.device_id == zwavejs_device }}"
          - condition: template
            value_template: "{{ trigger.event.data.command_class_name == 'Central Scene' }}"
        sequence:
          - choose:
            # IF scene 001
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.label == 'Scene 001' and trigger.event.data.value == 'KeyPressed' }}"
                sequence: !input scene_001_keypressed_actions
            # IF scene 001 2x
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.label == 'Scene 001' and trigger.event.data.value == 'KeyPressed2x' }}"
                sequence: !input scene_001_keypressed2x_actions
            # IF scene 001 3x
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.label == 'Scene 001' and trigger.event.data.value == 'KeyPressed3x' }}"
                sequence: !input scene_001_keypressed3x_actions
            # IF scene 001 4x
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.label == 'Scene 001' and trigger.event.data.value == 'KeyPressed4x' }}"
                sequence: !input scene_001_keypressed4x_actions
            # IF scene 001 5x
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.label == 'Scene 001' and trigger.event.data.value == 'KeyPressed5x' }}"
                sequence: !input scene_001_keypressed5x_actions
            # IF scene 002
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.label == 'Scene 002' and trigger.event.data.value == 'KeyPressed' }}"
                sequence: !input scene_002_keypressed_actions
            # IF scene 002 2x
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.label == 'Scene 002' and trigger.event.data.value == 'KeyPressed2x' }}"
                sequence: !input scene_002_keypressed2x_actions
            # IF scene 002 3x
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.label == 'Scene 002' and trigger.event.data.value == 'KeyPressed3x' }}"
                sequence: !input scene_002_keypressed3x_actions
            # IF scene 002 4x
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.label == 'Scene 002' and trigger.event.data.value == 'KeyPressed4x' }}"
                sequence: !input scene_002_keypressed4x_actions
            # IF scene 002 5x
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.label == 'Scene 002' and trigger.event.data.value == 'KeyPressed5x' }}"
                sequence: !input scene_002_keypressed5x_actions
            # IF release scene 001
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.label == 'Scene 001' and trigger.event.data.value == 'KeyReleased' }}"
                sequence: !input release_scene_001_actions
            # IF release scene 002
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.label == 'Scene 002' and trigger.event.data.value == 'KeyReleased' }}"
                sequence: !input release_scene_002_actions
            # IF hold scene 001
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.label == 'Scene 001' and trigger.event.data.value == 'KeyHeldDown' }}"
                sequence: !input hold_scene_001_actions
            # IF hold scene 002
              - conditions:
                  - condition: template
                    value_template: "{{ trigger.event.data.label == 'Scene 002' and trigger.event.data.value == 'KeyHeldDown' }}"
                sequence: !input hold_scene_002_actions
            # ELSE: unhandled scene label/value
            default:
              - service: system_log.write
                data:
                  level: debug
                  logger: "{{ logger }}"
                  message: "Activated scene '{{ trigger.event.data.label }}' with value '{{ trigger.event.data.value }}' for node '{{ zwavejs_device }}' ({{ trigger.event.data.node_id }})"
    # ELSE: unhandled zwavejs event
    default: []
